# .github/workflows/ci-cd.yaml
name: CI/CD Pipeline - Portfolio Manager BE

on:
  push:
    branches:
      - main
    paths:
      # 1. 修正: ルート直下にある全てのフォルダとファイル(.githubとk8sを除く)の変更をトリガー
      - '**' # <--- これでルート直下全体を指します

env:
  NEXUS_HOST: 192.168.56.1:8082
  IMAGE_NAME: portfolio-manager-be

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # ... ステップ 1, 2, 3 は変更なし ...
        
    - name: 4. Build and Push to Nexus
      uses: docker/build-push-action@v5
      with:
        # 2. 修正: ビルド元をリポジトリのルートに変更
        context: ./ 
        push: true
        tags: ${{ env.NEXUS_HOST }}/${{ env.IMAGE_NAME }}:latest
        # ... その他の設定は省略 ...
        
    - name: 6. Deploy to Minikube using kubectl
      run: |
        # Deployment/Service YAMLのパスも変更が必要です
        kubectl apply -f k8s/deployment.yaml # <--- 変更