# .github/workflows/ci-cd.yaml
name: CI/CD Pipeline - Portfolio Manager BE

on:
  # mainブランチにプッシュがあったときにトリガー
  push:
    branches:
      - main
    paths:
      - 'portfolio-manager-be/**'
      - 'k8s/**'

env:
  # ⚠️ Nexusのホストとポートに合わせてください
  NEXUS_HOST: 192.168.56.1:8082
  IMAGE_NAME: portfolio-manager-be

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 1. Checkout repository code
      uses: actions/checkout@v4

    # --- Docker ビルドとNexusへのプッシュ ---
    - name: 2. Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 3. Login to Nexus Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.NEXUS_HOST }}
        # GitHubリポジトリに登録したシークレットを使用します
        username: ${{ secrets.NEXUS_USERNAME }}
        password: ${{ secrets.NEXUS_PASSWORD }}

    - name: 4. Build and Push to Nexus
      uses: docker/build-push-action@v5
      with:
        context: ./portfolio-manager-be 
        push: true
        tags: ${{ env.NEXUS_HOST }}/${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    # --- Kubernetesへのデプロイ ---
    - name: 5. Set up kubectl (Kubernetes client)
      uses: azure/setup-kubectl@v4
      id: install

    - name: 6. Deploy to Minikube using kubectl
      run: |
        # Deployment/Service YAMLを適用
        kubectl apply -f portfolio-manager-be/k8s/deployment.yaml